### ISSUE TITLE
Umgang mit <note>

### ISSUE THREAD

**Issue by cthomasdta** [haoess/hidden-kosmos#10]
# Umgang mit `<note>`

unterscheiden `<persName>` in  `<note>` im Original und in `<note type="editorial">`: 
- `<persName>` in  `<note>` im Original sollen rein, dass klappt schon, z. B. "Olaf Römer" hier: http://www.deutschestextarchiv.de/parthey_msgermqu1711_1828/7
- Vorkommen in in `<note type="editorial">` sollen erstmal nicht mit in die Liste, z. B. wird hier http://www.deutschestextarchiv.de/nn_msgermqu2124_1827/165 Goethe nicht genannt, sondern nur als 'hoher Meister', Autor des Werther und der Metamorphose der Pflanzen indirekt angeführt. Anderes Beispiel hier http://www.deutschestextarchiv.de/nn_msgermqu2124_1827/156 wird "Gruithuisen" nicht erwähnt, sondern nur als "sonst achtbare[r] Naturforscher im südlichen Deutschland" bezeichnet.

**Comment by haoess** [comment]
fixed in 0b148b0
